services:
  - type: web
    name: sih-dr-project
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        value: NetraAI-db
      - key: SECRET_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: admin@teleophta.org
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_NAME
        value: Master District Admin
      - key: GOOGLE_CLIENT_ID
        value: 387784977439-ql7h183e12mgdvbfpcd2061d411p269c.apps.googleusercontent.com
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USE_TLS
        value: "True"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: BREVO_API_KEY
        sync: false
    healthCheckPath: /api/health
